name: React CI/CD pipeline
on: 
 push: 
  branches: 
   - main
jobs: 
 build: 
  runs-on: ubuntu-latest
  steps: 
    - name: Gitcheckout
      uses: actions/checkout@v4
    - name: to check the path for a directory
      run: pwd       
